#ifndef KEYBOARD_CONFIG_H
#define KEYBOARD_CONFIG_H

#include "stdint.h"

#define KEY_NUMBER 8
#define DEBOUNCE_DELAY 100

uint8_t KEY_TABLE[KEY_NUMBER] = {KEYBOARD_A, KEYBOARD_B, KEYBOARD_C, KEYBOARD_D,
    KEYBOARD_E, KEYBOARD_F, KEYBOARD_G, KEYBOARD_H};


#endif // KEYBOARD_CONFIG_H